# Generated by Django 5.1.6 on 2025-04-30 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_avatar', models.CharField(choices=[('default_avatar.png', 'Default Avatar'), ('avatar1.png', 'Avatar1'), ('avatar2.png', 'Avatar2'), ('avatar3.png', 'Avatar3'), ('avatar4.png', 'Avatar4')], default='default_avatar.png', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Tell us a little about yourself (max 250 chars).', max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
